# -*- coding: utf-8 -*-
"""Predicting Employee Attrition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hhvCl-oZiegxw5GL6aAdGqY_ojUh4X50
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from sklearn.metrics import accuracy_score

attrdata = pd.read_csv("/content/WA_Fn-UseC_-HR-Employee-Attrition.csv")

attrdata.head()

attrdata.drop(0,inplace=True)
attrdata.isnull().sum()

attrdata.dropna(axis=0,inplace=True)

attrdata.shape

gender_dict = attrdata["Gender"].value_counts()
gender_dict

attrdata['Gender'].value_counts().plot(kind='bar',color=['Green','blue'],title="Count of different gender")

performance_dict = attrdata["PerformanceRating"].value_counts()
performance_dict

attrdata['PerformanceRating'].value_counts().plot(kind='bar',color=['red','Green'],title="Performance Rating")

totalworkyears_dict = attrdata["TotalWorkingYears"].value_counts()
print(totalworkyears_dict)

attrdata['Gender'] = attrdata['Gender'].astype('category').cat.codes
attrdata['PerformanceRating'] = attrdata['PerformanceRating'].astype('category').cat.codes

attrdata['Attrition']= attrdata['Attrition'].astype('category').cat.codes
attrdata.head()

attrdata.info()

attrdata.describe()

attrdata.corr()

attrdata.columns

attrdata.shape

attrdata.head()

attrdata.tail()